[workspace]
members = [
    "bitlogin",
    "brainfuck",
    "brainfuck_macro",
    "brainfuck_procmacro",
    "iostream",
    "img2ascii",
    "huang_li",
    "mirage_tank",
    "ulogme",
    "webapi",
]
