[workspace]
members = [
    "bitlogin",
    "brainfuck",
    "brainfuck_macro",
    "calculator",
    "crc32fix",
    "iostream",
    "img2ascii",
    "mirage_tank",
    "md5",
    "ulogme",
    "webapi",
]
