[package]
name = "mirage_tank"
version = "1.0.0"
authors = ["Aloxaf <bailong104@gmail.com>"]

[dependencies]
image = "^0.19.0"
clap = {version = "^2.32.0", features = ["yaml"]}

[[bin]]
name = "mtank"
path = "src/main.rs"
