[package]
name = "crc32fix"
version = "1.0.0"
authors = ["Aloxaf <bailong104@gmail.com>"]
edition = "2018"

[dependencies]
png = "0.13.2"
crc = "1.8.1"
clap = { version = "2.32.0", features = ["yaml"] }
