[package]
name = "ulogme"
version = "0.1.0"
authors = ["Aloxaf <bailong104@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.45"
chrono = "0.4.6"
dbus = "0.6.3"
regex = "1.1.0"
log = "0.4.6"
env_logger = "0.6.0"

[build-dependencies]
cc = "1.0.26"
